eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    discovery:
      enabled: true
